apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager # Make sure this matches your existing ClusterSecretStore name
  target:
    name: kube-prometheus-stack-grafana # This must match the secret name Grafana expects
    template:
      type: Opaque
      data:
        admin-user: "{{ .admin-user }}"
        admin-password: "{{ .admin-password }}"
  data:
    - secretKey: admin-user
      remoteRef:
        key: kube-grafana-credentials
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: kube-grafana-credentials
        property: admin-password
