apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-creds
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: kube-n8n/db-creds
        property: username
    - secretKey: password
      remoteRef:
        key: kube-n8n/db-creds
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-container-env
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: kube-n8n/container-env
        property: DB_POSTGRESDB_USER
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: kube-n8n/container-env
        property: DB_POSTGRESDB_PASSWORD
