apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-superuser
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-db-superuser
    template:
      engineVersion: v2
      data:
        username: "postgres"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: kube-n8n/db-superuser
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-app-credentials
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-db-app
    template:
      engineVersion: v2
      data:
        username: "n8n"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: kube-n8n/db-app
        property: password
