apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`n8n.werrobots.cloud`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: n8n
      services:
        - name: n8n
          port: 80
