apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "28.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    ingressRoute:
      dashboard:
        enabled: true
