apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Ensure namespace exists in Git even though we created it
  - namespace.yaml

  # Deploy the repositories (Helm & Git)
  - repositories.yaml

  # Deploy the CRDs first
  - deployment-crds.yaml

  # Deploy the operator
  - deployment.yaml

  # Deploy custom resources (SecretStore) last
  - deployment-crs.yaml
