apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-cloudflare-cert-manager
  namespace: cert-manager
spec:
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: cloudflare-api-token-secret
    template:
      type: Opaque
  data:
    - secretKey: api-token
      remoteRef:
        key: kube-cloudflare-cert-manager
        property: api-token
