apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-container-env
  namespace: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: kube-pgadmin
        property: email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: kube-pgadmin
        property: password
