apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data
resources:
  - configmap.yaml
  - deployment.yaml
  - externalsecret.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
  - storage.yaml
